services:
  # Backend API service
  - type: web
    name: alu-chatbot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT --workers 2
    envVars:
      - key: DEPLOYMENT_ENV
        value: render
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend-domain.com
    healthCheckPath: /health

  # Frontend service (if you want to deploy the frontend directly to Render)
  # - type: web
  #   name: alu-chatbot-frontend
  #   env: static
  #   buildCommand: npm install && npm run build
  #   staticPublishPath: ./dist
  #   routes:
  #     - type: rewrite
  #       source: /*
  #       destination: /index.html
  #   envVars:
  #     - key: VITE_BACKEND_URL
  #       fromService:
  #         name: alu-chatbot-backend
  #         type: web
  #         envVarKey: RENDER_EXTERNAL_URL
