services:
  - type: web
    name: alu-chatbot-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python cache_models.py
    startCommand: python server.py
    envVars:
      - key: DEPLOYMENT_ENV
        value: render
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend-domain.com
      - key: TRANSFORMERS_OFFLINE
        value: "1"
    healthCheckPath: /health
