services:
  - type: web
    name: alu-chatbot-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: CORS_ALLOWED_ORIGINS
        value: "https://alu-student-companion.onrender.com,https://alu-companion.onrender.com,http://localhost:3000,http://localhost:3001"
      - key: MKL_NUM_THREADS
        value: 1
      - key: OMP_NUM_THREADS
        value: 1
