services:
  - type: web
    name: alu-chatbot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 2
    envVars:
      - key: DEPLOYMENT_ENV
        value: render
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend-domain.com
    healthCheckPath: /health
