services:
  - type: web
    name: alu-chatbot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DEPLOYMENT_ENV
        value: render
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend-domain.com
    healthCheckPath: /health
