services:
  - type: web
    name: alu-chatbot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: CORS_ALLOWED_ORIGINS
        value: http://localhost:3000,http://localhost:3001,https://alu-student-companion.onrender.com
